#! /usr/bin/python
import sys
from st7789v.interface import RaspberryPi
from st777789v import BufferedDisplay

with RaspberryPi() as rpi:
	display = BufferedDisplay(rpi, rotation=270)
	display.update()
	time.sleep(0.5)
	display.draw.rectangle((0, 0, 320, 240), fill='BLUE')
	display.update_partial(0, 0, 320, 120)

sys.exit(0)
